# Generated by Django 5.1.6 on 2025-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclimaticos',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='datosclimaticos',
            table='datos_climaticos',
        ),
    ]
